version: "3"
services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      # - my-mysql-data:/var/lib/mysql
      - /mnt/my-data-backup-ebs/mysql:/var/lib/mysql

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-container
    environment:
      MONGO_INITDB_USERNAME: admin
      MONGO_INITDB_PASSWORD: testtesttest
    volumes:
      # - my-mongodb-data:/data/db
      - /mnt/my-data-backup-ebs/mongo:/data/db

  studentstoreapp:
    image: dipkvts/studentstore:v2.0
    # build: ./
    ports:
      - 8080:8080
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_DBNAME: studentdb
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: testtesttest
    links:
      - mongodb:mongg
    depends_on:
      - mongodb

volumes:
  my-mongodb-data:
  my-mysql-data: